apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parasol-showroom
resources:
  - userdata-configmap.yaml
  - uiconfig-configmap.yaml
  - nginx-configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
