apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tempo.yaml
  - otel-collector.yaml
  - mlflow.yaml
  - mlflow-rbac.yaml
  - uwm.yaml
  - prometheusrule.yaml
  - servicemonitor.yaml
  - podmonitor-portal.yaml
  - uiplugin.yaml
