apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zz-quarantine-parasol-agent
spec:
  podSelector:
    matchLabels: {app: parasol-agent}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: openshift-dns}
      ports:
        - {protocol: UDP, port: 5353}
        - {protocol: TCP, port: 5353}
