apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  orchestratorConfig: guardrails-orchestrator-config
  guardrailsGatewayConfig: guardrails-gateway-config
  enableBuiltInDetectors: true
  enableGuardrailsGateway: true
  replicas: 1
  otelExporter:
    otlpProtocol: grpc
    otlpTracesEndpoint: http://otel-collector.observability.svc.cluster.local:4317
    enableTraces: true
